---
# Set up provisioner requirements and user expectations
- name: Display welcome banner and instructions
  debug:
    msg:
      - "================="
      - "== Provisioner =="
      - "================="
      - ""
      - "This provisioner will attempt to set up the target machine for AFSAS"
      - "development. Some steps will require additional information from you"
      - "such as logins, configuration files, etc."
      - ""
      - "However: it is safe to run and re-run this provisioner as you gain"
      - "access to these resources in case you do not currently have all of them."

- name: Warn on invalid Subversion username
  when: svn_server_username is undefined
  debug:
    msg:
      - "WARNING:"
      - "========"
      - "You did not provide a valid SVN username. Ansible will skip all steps requiring SVN content."

- name: Warn on invalid Subversion password
  when: svn_server_password is undefined
  debug:
    msg:
      - "WARNING:"
      - "========"
      - "You did not provide a valid SVN password. Ansible will skip all steps requiring SVN content."
