---
# Package installation/configuration tasks
- name: Get basic packages
  become: yes
  package:
    name:
      - opensc
      - pcscd
      - pcsc-tools
      - subversion
      - ant
      - software-properties-common
      - '{{ jdk_version }}'
      
      # Add your preferred packages below:
      - tree
      - silversearcher-ag
      - zsh
      - keepassx
      - terminator
      - emacs
      - git
      - make
      - gnome-tweaks
      - arc-theme
      - moka-icon-theme
    state: latest
    update_cache: yes

- name: Download VS Code
  when: ansible_distribution == "Ubuntu"
  become: yes
  community.general.snap:
    name: code
    classic: true

- name: Make Z Shell default shell option for current user
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh  

- name: Apply dotfiles from ../resources
  block:
    - name: Create backup dotfiles folder
      ansible.builtin.file:
        path: "{{ user_home }}/.dotfiles_backup"
        state: directory

    - name: Backup existing dotfiles
      block:
        - name: Previous .zshrc
          ansible.builtin.copy:
            src: "{{ user_home }}/.zshrc"
            dest: "{{ user_home }}/.dotfiles_backup/.zshrc-{{ ansible_date_time.iso8601 }}"
          when: '"{{ user_home }}/.zshrc" is file'
        - name: Previous .gitconfig
          ansible.builtin.copy:
            src: "{{ user_home }}/.gitconfig"
            dest: "{{ user_home }}/.dotfiles_backup/.gitconfig-{{ ansible_date_time.iso8601 }}"
          when: '"{{ user_home }}/.gitconfig" is file'
        - name: Previous .emacs.d
          ansible.builtin.copy:
            src: "{{ user_home }}/.emacs.d"
            dest: "{{ user_home }}/.dotfiles_backup/.emacs.d-{{ ansible_date_time.iso8601 }}"
          when: '"{{ user_home }}/.emacs.d" is directory'
  
    - name: Install ../resources dotfiles
      block:
        - name: New .zshrc
          ansible.builtin.copy:
            src: "{{ playbook_dir }}/roles/utils/resources/.zshrc"
            dest: "{{ user_home }}/.zshrc"
        - name: New .gitconfig
          ansible.builtin.copy:
            src: "{{ playbook_dir }}/roles/utils/resources/.gitconfig"
            dest: "{{ user_home }}/.gitconfig"
        - name: New .emacs.d
          ansible.builtin.copy:
            src: "{{ playbook_dir }}/roles/utils/resources/.emacs.d"
            dest: "{{ user_home }}/.emacs.d"

- name: Assign $JAVA_HOME variable
  become: yes
  lineinfile:
    path: "{{ profile_location }}"
    line: "export JAVA_HOME=\"{{ java_home }}\";"

- name: Configure saving subversion CLI/svn passwords
  block:
    - name: Force svn to generate .subversion config folder
      command: svn --version

    - name: Add password settings to .subversion/server
      ansible.builtin.blockinfile:
        path: "{{ user_home }}/.subversion/servers"
        backup: yes
        block: |
          store-passwords = yes
          store-plaintext-passwords = yes

- name: Configuration notices
  debug:
    msg:
      - "The utils role has made the following changes:"
      - " - Exported $JAVA_HOME in {{ profile_location }}."
      - " - Configured Subversion CLI to store plaintext passwords."
