---
# Package installation/configuration tasks
- name: Get basic packages
  become: yes
  package:
    name:
      - opensc
      - pcscd
      - pcsc-tools
      - subversion
      - ant
      - software-properties-common
      - '{{ jdk_version }}'
      
      # Add your preferred packages below:
      - tree
      - silversearcher-ag
      - zsh
      - keepassx
      - terminator
      - emacs
      - git
      - make
      - gnome-tweaks
    state: latest
    update_cache: yes

- name: Optionally download VS Code
  when: ansible_distribution == "Ubuntu"
  snap:
    name: code
    classic: yes

- name: Assign $JAVA_HOME variable
  become: yes
  lineinfile:
    path: "{{ profile_location }}"
    line: "export JAVA_HOME=\"{{ java_home }}\";"

- name: Configure saving subversion CLI/svn passwords
  block:
    - name: Force svn to generate .subversion config folder
      command: svn --version

    - name: Add password settings to .subversion/server
      ansible.builtin.blockinfile:
        path: "{{ user_home }}/.subversion/servers"
        backup: yes
        block: |
          store-passwords = yes
          store-plaintext-passwords = yes

- name: Configuration notices
  debug:
    msg:
      - "The utils role has made the following changes:"
      - " - Exported $JAVA_HOME in {{ profile_location }}."
      - " - Configured Subversion CLI to store plaintext passwords."
